# Generated by Django 4.1.3 on 2022-12-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intvelocity', models.CharField(max_length=3)),
                ('finvelocity', models.CharField(max_length=3)),
                ('ETime', models.CharField(max_length=5)),
            ],
        ),
    ]
