# Generated by Django 4.1.3 on 2022-12-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_csv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv',
            old_name='Intvelocity',
            new_name='Intial_velocity',
        ),
        migrations.RenameField(
            model_name='csv',
            old_name='ETime',
            new_name='Time_taken',
        ),
        migrations.RenameField(
            model_name='csv',
            old_name='finvelocity',
            new_name='final_velocity',
        ),
    ]
