# Generated by Django 4.1.3 on 2022-12-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_intial_velocity_csv_intial_velocity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='filelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('file_name', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='csv',
        ),
    ]
