# Generated by Django 4.1.3 on 2022-12-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_filelog_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelog',
            name='algorithm',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
