# Generated by Django 4.1.3 on 2023-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_candidate_algo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_algo',
            name='filename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate_algo',
            name='forecast',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate_algo',
            name='humid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate_algo',
            name='output',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate_algo',
            name='sky',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate_algo',
            name='temperature',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate_algo',
            name='water',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate_algo',
            name='wind',
            field=models.CharField(max_length=50),
        ),
    ]
