# Generated by Django 4.1.3 on 2023-02-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_candidate_algo_filename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnosis_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_id', models.CharField(max_length=50)),
                ('fever', models.CharField(max_length=50)),
                ('medicine', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='disease_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_id', models.CharField(max_length=50)),
                ('fever', models.CharField(max_length=50)),
                ('medicine', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='candidate_algo',
        ),
        migrations.RenameField(
            model_name='filelog',
            old_name='algorithm',
            new_name='instance_type',
        ),
    ]
