# Generated by Django 4.1.3 on 2023-03-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_instances_delete_active_instance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='diagnosis_instance',
        ),
        migrations.DeleteModel(
            name='disease_instance',
        ),
    ]
