# Generated by Django 4.1.3 on 2023-03-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_instances_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelog',
            name='aliasname',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
