# Generated by Django 4.1.3 on 2023-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_filelog_aliasname'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelog',
            name='file_size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='filelog',
            name='time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
