# Generated by Django 4.1.3 on 2023-04-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_filelog_file_size_filelog_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filelog',
            old_name='time',
            new_name='upload_time',
        ),
    ]
