# Generated by Django 4.2.1 on 2023-05-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_remove_filelog_id_filelog_final_result_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filelog',
            old_name='upload_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='instances',
            name='id',
        ),
        migrations.AlterField(
            model_name='instances',
            name='instance_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
