# Generated by Django 4.2.1 on 2023-05-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_remove_usersinfo_id_alter_usersinfo_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelog',
            name='aliasname',
            field=models.CharField(default='SOME STRING', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='file_size',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
