# Generated by Django 4.2.1 on 2023-05-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_alter_instances_algorithm_alter_instances_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instances',
            name='algorithm',
            field=models.IntegerField(),
        ),
    ]
