# Generated by Django 4.2.1 on 2023-05-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_alter_instances_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instances',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
